version: '3.8'

services:
  mysql1:
    image: mysql:latest
    container_name: write-db
    environment:
      MYSQL_ROOT_PASSWORD: root1
      MYSQL_USER: bill1
      MYSQL_PASSWORD: root1
      MYSQL_DATABASE: write_db
    ports:
      - "3306:3306"
    volumes:
      - ./init_write_db.sql:/docker-entrypoint-initdb.d/init.sql

  mysql2:
    image: mysql:latest
    container_name: read-db
    environment:
      MYSQL_ROOT_PASSWORD: root2
      MYSQL_USER: bill2
      MYSQL_PASSWORD: root2
      MYSQL_DATABASE: read_db
    ports:
      - "3307:3306"
    volumes:
      - ./init_read_db.sql:/docker-entrypoint-initdb.d/init.sql
