spring:
  application:
    name: multiple-datasource
  datasource:
#    initialize: false
    write-db:
      url: jdbc:mysql://localhost:3306/write_db?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root1
      driverClassName: com.mysql.cj.jdbc.Driver
    read-db:
      url: jdbc:mysql://localhost:3307/read_db?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root2
      driverClassName: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
